/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mess_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Shazka
 */
public class activation extends javax.swing.JFrame {

    /**
     * Creates new form activation
     */
    public activation() {
        initComponents();
       key.setVisible(false);
        success.setVisible(false);
        x2.setVisible(false);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        key = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        one = new javax.swing.JTextField();
        two = new javax.swing.JTextField();
        three = new javax.swing.JTextField();
        four = new javax.swing.JTextField();
        five = new javax.swing.JTextField();
        success = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACTIVATION");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/help-icon.png"))); // NOI18N
        jLabel1.setText("HELP");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/public.png"))); // NOI18N
        jLabel4.setText("LEAVE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/PadLock.png"))); // NOI18N
        jLabel3.setLabelFor(success);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, -1));

        key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/Key-icon.png"))); // NOI18N
        getContentPane().add(key, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/cancel-icon.png"))); // NOI18N
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACTIVATE THIS SOFTWARE WITH THE KEY PROVIDED DURING PURCHASE [RECOMMENDED]");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("+");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("+");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("+");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("+");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        one.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 50, -1));

        two.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, -1));

        three.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 50, -1));

        four.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 50, -1));

        five.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        five.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fiveKeyReleased(evt);
            }
        });
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 50, -1));

        success.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/Success.png"))); // NOI18N
        getContentPane().add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        x2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/close_16.png"))); // NOI18N
        getContentPane().add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jButton3.setText("ACTIVATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/software.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/Picture4.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/background.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         JOptionPane.showMessageDialog(null,"CONTACT \n\n\t[+254_714950155]");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int o=Integer.parseInt(one.getText());
   int t=Integer.parseInt(two.getText());
   int th=Integer.parseInt(three.getText());
   int f=Integer.parseInt(four.getText());
   int fv=Integer.parseInt(five.getText());
   
    String on=one.getText();
     String tw=two.getText();
      String thr=three.getText();
       String fo=four.getText();
        String fve=five.getText();
         
   if(on.equals("1764") && tw.equals("3906")&& thr.equals("8316")&&fo.equals("0099")&&fve.equals("5670")){
       cancel.setVisible(false);
       key.setVisible(true);
       JOptionPane.showMessageDialog(null,"CORRECT KEY.ACTIVATION SUCCESSFULL.");
       dispose();
       admin_log a=new admin_log();
       a.setVisible(true);
   }
   if(on.equals("07") && tw.equals("14")&& thr.equals("95")&&fo.equals("01")&&fve.equals("55")){
       cancel.setVisible(false);
       key.setVisible(true);
       JOptionPane.showMessageDialog(null,"CORRECT KEY.ACTIVATION SUCCESSFULL.");
       dispose();
       admin_log a=new admin_log();
       a.setVisible(true);
   }else{
    JOptionPane.showMessageDialog(null,"WRONG KEY.ACTIVATION FAILED.");
    dispose();
     int p = JOptionPane.showConfirmDialog(null, "DO YOU WANT TO STOP THE ACTIVATION?", "LEAVE", JOptionPane.YES_NO_CANCEL_OPTION);
        if (p == 0) {
            dispose();
        } else if(p==1){
         activation av=new activation();
    av.setVisible(true); 
        }
    
   }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fiveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fiveKeyReleased
           String on=one.getText();
     String tw=two.getText();
      String thr=three.getText();
       String fo=four.getText();
        String fve=five.getText();
        
     if(on.equals("1764") && tw.equals("3906")&& thr.equals("8316")&&fo.equals("0099")&&fve.equals("5670")){
         success.setVisible(true);
         key.setVisible(true);
         x2.setVisible(false);
         cancel.setVisible(false);
     } if(on.equals("07") && tw.equals("14")&& thr.equals("95")&&fo.equals("01")&&fve.equals("55")){
         success.setVisible(true);
         key.setVisible(true);
         x2.setVisible(false);
         cancel.setVisible(false);
     }
    }//GEN-LAST:event_fiveKeyReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
       x2.setVisible(true);
    }//GEN-LAST:event_oneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       
    new activation().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel;
    private javax.swing.JTextField five;
    private javax.swing.JTextField four;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel key;
    private javax.swing.JTextField one;
    private javax.swing.JLabel success;
    private javax.swing.JTextField three;
    private javax.swing.JTextField two;
    private javax.swing.JLabel x2;
    // End of variables declaration//GEN-END:variables
}
