/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author shazka
 */
public class admin_details extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form admin_details
     */
    public admin_details() {
        initComponents();
        // progress.setIndeterminate(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        tab_com = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRactivate_audio = new javax.swing.JRadioButton();
        jRdeactivate_audio = new javax.swing.JRadioButton();
        jRactivate_tray = new javax.swing.JRadioButton();
        jRdeactivate_tray = new javax.swing.JRadioButton();
        tab_com1 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/loading-1.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/exclamation.png"))); // NOI18N
        jButton5.setText("SERVER INSTALL 32_BIT");
        jButton5.setToolTipText("CLICK TO INSTALL A SERVER.");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 30));

        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/exclamation.png"))); // NOI18N
        jButton9.setText("SERVER INSTALL 64_BIT");
        jButton9.setToolTipText("CLICK TO INSTALL A SERVER.");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 28));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/table_add.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/data_add.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/data_remove.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/1 (27).png"))); // NOI18N
        jButton8.setText(" Manage Users");
        jButton8.setToolTipText("THE MAIN STAFF WINDOW.");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 140, 50));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/back_alt.png"))); // NOI18N
        jLabel11.setText("[BACK]");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/public.png"))); // NOI18N
        jLabel12.setText("[EXIT]");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 60, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USERS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 40, -1));

        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("RUN THE SERVER");
        jRadioButton2.setToolTipText("CLICK TO RUN THE SERVER");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("RUN THE SERVER");
        jRadioButton3.setToolTipText("CLICK TO RUN THE SERVER");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        tab_com.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tab_com.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT AN OPTION--", "T_one_two", "T_three_four", "std_details", "settings" }));
        getContentPane().add(tab_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/table_remove.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SETTINGS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 70, -1));

        buttonGroup1.add(jRactivate_audio);
        jRactivate_audio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRactivate_audio.setForeground(new java.awt.Color(51, 255, 51));
        jRactivate_audio.setText("ACTIVATE SOUND PROMPT DURING START UP");
        jRactivate_audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRactivate_audioActionPerformed(evt);
            }
        });
        getContentPane().add(jRactivate_audio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 310, -1));

        buttonGroup1.add(jRdeactivate_audio);
        jRdeactivate_audio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRdeactivate_audio.setForeground(new java.awt.Color(51, 255, 51));
        jRdeactivate_audio.setText("DEACTIVATE VOICE PROMPT DURING START UP");
        jRdeactivate_audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdeactivate_audioActionPerformed(evt);
            }
        });
        getContentPane().add(jRdeactivate_audio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        buttonGroup2.add(jRactivate_tray);
        jRactivate_tray.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRactivate_tray.setForeground(new java.awt.Color(51, 255, 51));
        jRactivate_tray.setText("ACTIVATE TOUCH SCREEN DURING START UP");
        jRactivate_tray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRactivate_trayActionPerformed(evt);
            }
        });
        getContentPane().add(jRactivate_tray, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 320, -1));

        buttonGroup2.add(jRdeactivate_tray);
        jRdeactivate_tray.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRdeactivate_tray.setForeground(new java.awt.Color(51, 255, 51));
        jRdeactivate_tray.setText("DEACTIVATE  TOUCH SCREEN   DURING START UP");
        jRdeactivate_tray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdeactivate_trayActionPerformed(evt);
            }
        });
        getContentPane().add(jRdeactivate_tray, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        tab_com1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tab_com1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT AN OPTION--", "T_one_two", "T_three_fourr" }));
        getContentPane().add(tab_com1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, -1));

        jButton10.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jButton10.setText("DROP");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATABASES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TABLES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SERVERS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/admin_back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        getAccessibleContext().setAccessibleName("ADMIN DETAILS");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
//        dispose();
//        admin_log ad = new admin_log();
//        ad.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        //process process=new processBuilder("K:\\New folder\\myJavaApp\\test\\WampServer2.1e-x32.exe","param1","param2").start();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "F:\\New folder\\myJavaApp\\test\\WampServer2.1e-x32.exe");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\wamp\\wampmanager.exe");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
//        dispose();
//        admin_edit_details aed = new admin_edit_details();
//        aed.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "F:\\New folder\\myJavaApp\\test\\Wampserver2.4-x64.exe");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\wamp\\wampmanager.exe");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String combo = (String) tab_com1.getSelectedItem();
        String dbnam = "exams_database";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            if (combo.equals("T_one_two")) {
                String tb = "DROP TABLE " + combo + "";
                s.execute(tb);
            }
            if (combo.equals("T_three_four")) {
                String tb = "DROP TABLE " + combo + "";
                s.execute(tb);
            }
            if (combo.equals("std_details")) {
                String tb = "DROP TABLE " + combo + "";
                s.execute(tb);
            }

            JOptionPane.showMessageDialog(null, "table " + combo + " has been cleared.");
            cn.close();
        } catch (SQLException f) {
            JOptionPane.showMessageDialog(null, f);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
//            String val = i + "F";
//            float f = Float.valueOf(val);
//            this.setOpacity(f);
//
//            try {
//                Thread.sleep(100);
//
//            } catch (Exception e) {
//
//            }
//
//        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        String combo = (String) tab_com.getSelectedItem();
        String dbnam = "exams_database";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            if (combo.equals("T_one_two")) {
                String tb = "CREATE TABLE " + combo + "(reg_no VARCHAR(255),mat1 INT,mat2 INT,mat3 INT,eng1 INT,eng2 INT,eng3 INT,kis1 INT,kis2 INT,kis3 INT,bio1 INT,bio2 INT,bio3 INT,che1 INT,che2 INT,che3 INT,phy1 INT,phy2 INT,phy3 INT,his1 INT,his2 INT,his3 INT,geo1 INT,geo2 INT,geo3 INT,cre1 INT,cre2 INT,cre3 INT,soc1 INT,soc2 INT,soc3 INT,agr1 INT,agr2 INT,agr3 INT,com1 INT,com2 INT,com3 INT,cmp1 INT,cmp2 INT,cmp3 INT,art1 INT,art2 INT,art3 INT,mus1 INT,mus2 INT,mus3 INT,hsc1 INT,hsc2 INT,hsc3 INT,PRIMARY KEY(reg_no))";
                s.execute(tb);
            }
            if (combo.equals("T_three_four")) {
                String tb = "CREATE TABLE " + combo + "(reg_no VARCHAR(255) NOT NULL, mat1 INT,mat2 INT,mat3 INT,eng1 INT,eng2 INT,eng3 INT,kis1 INT,kis2 INT,kis3 INT,bio1 INT,bio2 INT,bio3 INT,che1 INT,che2 INT,che3 INT,phy1 INT,phy2 INT,phy3 INT,his1 INT,his2 INT,his3 INT,geo1 INT,geo2 INT,geo3 INT,cre1 INT,cre2 INT,cre3 INT,soc1 INT,soc2 INT,soc3 INT,agr1 INT,agr2 INT,agr3 INT,com1 INT,com2 INT,com3 INT,cmp1 INT,cmp2 INT,cmp3 INT,art1 INT,art2 INT,art3 INT,mus1 INT,mus2 INT,mus3 INT,hsc1 INT,hsc2 INT,hsc3 INT,PRIMARY KEY(reg_no))";
                s.execute(tb);
            }
            if (combo.equals("std_details")) {
                String tb = "CREATE TABLE " + combo + "(reg_no VARCHAR(255)NOT NULL,f_name VARCHAR(255),s_name VARCHAR(255),gender VARCHAR(25),dorm VARCHAR(255),kin_name VARCHAR(255),kin_no VARCHAR(255),PRIMARY KEY(reg_no))";
                s.execute(tb);
            } if (combo.equals("settings")) {
                String tb = "CREATE TABLE " + combo + "(my_id_code INT NOT NULL AUTO_INCREMENT,my_voice_code INT,PRIMARY KEY(my_id_code))";
                s.execute(tb);
                
                 String insert_audio="INSERT INTO settings(my_id_code,my_voice_code) VALUES(1,1)";
                 String insert_tray="INSERT INTO settings(my_id_code,my_voice_code) VALUES(2,1)";
                 s.executeUpdate(insert_audio);
                 s.executeUpdate(insert_tray);   
            }

            JOptionPane.showMessageDialog(null, "Table " + combo + " has been created");
            //JOptionPane.showMessageDialog(null, "PLEASE SELECT THE [UPDATE RADIO BUTTON TO UPDATE TABLE]" + combo + ".");
            cn.close();
        } catch (SQLException f) {
            JOptionPane.showMessageDialog(null, "Table aleady exists.");
            //ou.setText("table NAMES already exists");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        String combo = (String) tab_com1.getSelectedItem();
        String dbnam = "exams_database";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            if (combo.equals("T_one_two")) {
                String tb = "TRUNCATE TABLE " + combo + "";
                s.execute(tb);
            }
            if (combo.equals("T_three_four")) {
                String tb = "TRUNCATE TABLE " + combo + "";
                s.execute(tb);
            }
            if (combo.equals("std_details")) {
                String tb = "TRUNCATE TABLE " + combo + "";
                s.execute(tb);
            }

            JOptionPane.showMessageDialog(null, "TABLE" + combo + " HAS BEEN CLEARED.");

            cn.close();
        } catch (SQLException f) {
           JOptionPane.showMessageDialog(null, "Some thing went wrong.\nContact Administrator.");

        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String pwd = "";
        String dbnm = "?";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url + dbnm, usernam, pwd);
            try {
                Statement st = con.createStatement();
                JOptionPane.showMessageDialog(null, "YOU ARE CREATING A NEW DATABASE");
                String database = JOptionPane.showInputDialog(null, "DATABASE NAME.");
                int p = JOptionPane.showConfirmDialog(null, "Do you want to create DATABASE " + database + "?", "CREATE.", JOptionPane.YES_NO_CANCEL_OPTION);
                if (p == 0) {

                    st.executeUpdate("CREATE DATABASE " + database);

                    JOptionPane.showMessageDialog(null, "Successfully created");

                } else {
                    con.close();

                }

            } catch (SQLException s) {
                JOptionPane.showMessageDialog(null, "Some thing went wrong.\nContact Administrator.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        String pwd = "";
        String dbnm = "?";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url + dbnm, usernam, pwd);
            try {
                Statement st = con.createStatement();
                JOptionPane.showMessageDialog(null, "YOU ARE DELETING AN EXISTING DATABASE");
                String database = JOptionPane.showInputDialog(null, "DATABASE NAME.");
                int p = JOptionPane.showConfirmDialog(null, "Do you want to delete DATABASE " + database + "?", "DELETE.", JOptionPane.YES_NO_CANCEL_OPTION);
                if (p == 0) {

                    st.executeUpdate("DROP DATABASE " + database);

                    JOptionPane.showMessageDialog(null, "Successfully deleted");

                } else {
                    con.close();
                    JOptionPane.showMessageDialog(null, "THAT DATABASE DOES NOT EXIST.\n\nTHANK YOU.");
                }

            } catch (SQLException s) {
                JOptionPane.showMessageDialog(null, "Some thing went wrong.\nContact Administrator.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jRactivate_audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRactivate_audioActionPerformed
        String intro = "tab_intro";
        String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            s.execute("UPDATE settings SET my_voice_code = 1 WHERE my_id_code = 1");  
        
            JOptionPane.showMessageDialog(null, "Changes have been set");
            cn.close();
        } catch (SQLException f) {
           JOptionPane.showMessageDialog(null, "Some thing went wrong.\nContact Administrator.");
            
        }
    }//GEN-LAST:event_jRactivate_audioActionPerformed

    private void jRdeactivate_audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdeactivate_audioActionPerformed
        String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            s.execute("UPDATE settings SET my_voice_code = 2 WHERE my_id_code = 1");  
        
            JOptionPane.showMessageDialog(null, "Changes have been set");
            cn.close();
        } catch (SQLException f) {
           JOptionPane.showMessageDialog(null, "Some thing went wrong.\nContact Administrator.");
            
        }
    }//GEN-LAST:event_jRdeactivate_audioActionPerformed

    private void jRactivate_trayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRactivate_trayActionPerformed
        String intro = "tab_intro";
        String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            s.execute("UPDATE settings SET my_voice_code = 1 WHERE my_id_code = 2");  
        
            JOptionPane.showMessageDialog(null, "Changes have been set");
            cn.close();
        } catch (SQLException f) {
           JOptionPane.showMessageDialog(null, "Some thing went wrong.\nContact Administrator.");
            
        }
    }//GEN-LAST:event_jRactivate_trayActionPerformed

    private void jRdeactivate_trayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdeactivate_trayActionPerformed
        String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            s.execute("UPDATE settings SET my_voice_code = 2 WHERE my_id_code = 2");  
        
            JOptionPane.showMessageDialog(null, "Changes have been set");
            cn.close();
        } catch (SQLException f) {
            JOptionPane.showMessageDialog(null, "Some thing went wrong.\nContact Administrator.");
            
        }
    }//GEN-LAST:event_jRdeactivate_trayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRactivate_audio;
    private javax.swing.JRadioButton jRactivate_tray;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRdeactivate_audio;
    private javax.swing.JRadioButton jRdeactivate_tray;
    private javax.swing.JComboBox tab_com;
    private javax.swing.JComboBox tab_com1;
    // End of variables declaration//GEN-END:variables

 
}
