/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Karis
 */
public class Change_Pswd extends javax.swing.JDialog {
        
         Connection conn = null;
       PreparedStatement pst =  null;
       ResultSet rs = null;
    /**
     * Creates new form Change_Pswd
     */
    public Change_Pswd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTregNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCuser = new javax.swing.JComboBox();
        jPcurrent_pswd = new javax.swing.JPasswordField();
        jPnew_pswd2 = new javax.swing.JPasswordField();
        jPnew_pswd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Select User :");

        jTregNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTregNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTregNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTregNoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Enter RegNo :");

        jTname.setEditable(false);
        jTname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Enter Current Pswd :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Enter New Pswd :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Confirm New Pswd :");

        jButton1.setText("CHANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCuser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Staff", "Student" }));

        jPcurrent_pswd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPnew_pswd2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPnew_pswd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTregNo)
                                .addComponent(jCuser, 0, 179, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPcurrent_pswd)
                                .addComponent(jTname, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(jPnew_pswd2)
                                .addComponent(jPnew_pswd))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(208, 208, 208))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(206, 206, 206)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCuser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTregNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPcurrent_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnew_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnew_pswd2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTregNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTregNoKeyReleased
            key_released();

        // TODO add your handling code here:
    }//GEN-LAST:event_jTregNoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        change();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Change_Pswd dialog = new Change_Pswd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPcurrent_pswd;
    private javax.swing.JPasswordField jPnew_pswd;
    private javax.swing.JPasswordField jPnew_pswd2;
    private javax.swing.JTextField jTname;
    private javax.swing.JTextField jTregNo;
    // End of variables declaration//GEN-END:variables

          public void change(){
        
             Connect connectobj = new Connect();
        conn = connectobj.connectdb();
        
        String user=(String)jCuser.getSelectedItem();
        String regno=jTregNo.getText();
        String c_pswd=jPcurrent_pswd.getText();
        String n_pswd1=jPnew_pswd.getText();
        String n_pswd2=jPnew_pswd2.getText();
        
        if(user.equals("Student")){
        
             try {
            Statement stm = conn.createStatement();
            String sql = "select * from student_reg where Reg_No = '" + regno + "'";
            rs = stm.executeQuery(sql);

            while (rs.next()) {
                    //out_table.setModel(DbUtils.resultSetToTableModel(rs));
                    String sname = rs.getString("S_Name");                    
                    String fname = rs.getString("F_Name");                    
                    String mname = rs.getString("M_Name");                    
                    String reg_no = rs.getString("Reg_No");              
                    String idno = rs.getString("Id_No");
                    String cos = rs.getString("Course");
                    String faculty = rs.getString("Faculty");
                    
                    String phone = rs.getString("Phone_No");                    
                    String email = rs.getString("Email");                    
                    String gender = rs.getString("Gender");                    
                    String doa = rs.getString("D_o_A");              
                    String dog = rs.getString("D_o_G");
                   String date = rs.getString("Date");              
                    String time = rs.getString("Time");
                   int bal = rs.getInt("Balance");              
                    String pswd = rs.getString("Pswd");
                        
                   if(c_pswd.equals(pswd)){
                       
                       if(n_pswd1.equals(n_pswd2)){
                       
                             try {
            //String sgl="INSERT INTO `banking`(`accnt`, `Name`, `IdNo.`, `PhoneNo`, `Email`, `Nationality`, `Occupation`, `Gender`, `MaritualStatus`, `Date`, `Balance`) VALUES ("342","karis","867","34546","karijavade","kenyan","programmer","male","single","hrjh","44232"")";
            String sql2 = "UPDATE `student_reg` SET `Pswd`='"+n_pswd2+"' WHERE `Reg_No`='"+regno+"'";

            pst = conn.prepareStatement(sql2);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Password Changed Successfully");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
                           
                       }else{
                       JOptionPane.showMessageDialog(null, "Be Certain To confirm your new pswd");
                       }
                   
                   }else{
                   
                       JOptionPane.showMessageDialog(null, "Incorrect Password in the Current Password Field");
                   } 
                   
                    
                 }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        
        }else 
            if(user.equals("Staff")){
                
                 try {
            Statement stm = conn.createStatement();
            String sql = "select * from staff_details where StaffNo = '" + regno + "'";
            rs = stm.executeQuery(sql);

            while (rs.next()) {
                    //out_table.setModel(DbUtils.resultSetToTableModel(rs));
                    String sname = rs.getString("Sname");                    
                    String fname = rs.getString("Fname");                    
                    String mname = rs.getString("Mname");                    
                                
                    String pswd = rs.getString("Pswd");
                        
                   if(c_pswd.equals(pswd)){
                       
                       if(n_pswd1.equals(n_pswd2)){
                       
                             try {
            //String sgl="INSERT INTO `banking`(`accnt`, `Name`, `IdNo.`, `PhoneNo`, `Email`, `Nationality`, `Occupation`, `Gender`, `MaritualStatus`, `Date`, `Balance`) VALUES ("342","karis","867","34546","karijavade","kenyan","programmer","male","single","hrjh","44232"")";
            String sql2 = "UPDATE `staff_details` SET `Pswd`='"+n_pswd2+"' WHERE `Reg_No`='"+regno+"'";

            pst = conn.prepareStatement(sql2);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Password Changed Successfully");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
                           
                       }else{
                       JOptionPane.showMessageDialog(null, "Be Certain To confirm your new pswd");
                       }
                   
                   }else{
                   
                       JOptionPane.showMessageDialog(null, "Incorrect Password in the Current Password Field");
                   } 
                   
                    
                 }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
            
            }            
            else{
                JOptionPane.showMessageDialog(null, "Kindly Select A valid User");
            }
        
        
        }
          
          public void key_released(){
          
              
        
        Connect connectobj = new Connect();
        conn = connectobj.connectdb();

        String user=(String)jCuser.getSelectedItem();
        String regno=jTregNo.getText();
        
        if(user.equals("Student")){
            try {
                Statement stm = conn.createStatement();
                String sql = "select * from student_reg where Reg_No = '" + regno + "'";
                rs = stm.executeQuery(sql);

                while (rs.next()) {
                    //out_table.setModel(DbUtils.resultSetToTableModel(rs));
                    String sname = rs.getString("S_Name");
                    String fname = rs.getString("F_Name");
                    String mname = rs.getString("M_Name");
                    String pswd = rs.getString("Pswd");

                    jTname.setText(sname+" "+fname+" "+mname);

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());

            }
        }
        else
        if(user.equals("Staff")){

            try {
                Statement stm = conn.createStatement();
                String sql = "select * from staff_details where StaffNo = '" + regno + "'";
                rs = stm.executeQuery(sql);

                while (rs.next()) {
                    //out_table.setModel(DbUtils.resultSetToTableModel(rs));
                    String sname = rs.getString("Sname");
                    String fname = rs.getString("Fname");
                    String mname = rs.getString("Mname");
                    String pswd = rs.getString("Pswd");

                    jTname.setText(sname+" "+fname+" "+mname);

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());

            }

        }
        else{
            JOptionPane.showMessageDialog(null, "kindly select a user to continue");
        }
          
          }
          
          public void clear(){
          jTregNo.setText("");
          jPcurrent_pswd.setText("");
          jPnew_pswd.setText("");
          jPnew_pswd2.setText("");
          jTname.setText("");
          jCuser.setSelectedIndex(0);
          
          
          }

}



