package mess_system;

import java.io.FileOutputStream;
import java.io.*;
import java.util.*;
import java.sql.*; 
import com.itextpdf.text.*;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.*;
import java.awt.Desktop;
import javax.swing.JOptionPane;
public class jdbc_pdf_report {  
    
    Font ffont = new Font(Font.FontFamily.UNDEFINED, 6, Font.ITALIC);
    
     
    
        public void  mainh() throws Exception{
                
             
            
             PdfPCell table_cell;
            
                /* Create Connection objects */
                Class.forName ("com.mysql.jdbc.Driver"); 
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mess", "root", "");
                Statement stmt = conn.createStatement();
                /* Define the SQL query */
                ResultSet query_set = stmt.executeQuery("SELECT * FROM records");
                 PdfWriter writer ;
                /* Step-2: Initialize PDF documents - logical objects */
                Document my_pdf_report = new Document();
                PdfWriter.getInstance(my_pdf_report, new FileOutputStream("records.pdf"));
                my_pdf_report.open();
                //we have four columns in our table
                PdfPTable my_report_table = new PdfPTable(12);
                //create a cell object
                class MyFooter extends PdfPageEventHelper 
        {
             Font ffont = new Font(Font.FontFamily.UNDEFINED, 6, Font.ITALIC);

             public void onEndPage(PdfWriter writer, Document document) {
                 PdfContentByte cb = writer.getDirectContent();
                 Phrase footer = new Phrase("Report card designed and generated by Shazka Systems.", ffont);

                 ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                         footer,
                         (document.right() - document.left()) / 2 + document.leftMargin(),
                         document.bottom() - 10, 0);
             }
         }
               
                
               
//                 Font ffont = new Font(Font.FontFamily.UNDEFINED, 6, Font.ITALIC);
//                 PdfContentByte cb = writer.getDirectContent();
//                 Phrase footer = new Phrase("Report card designed and generated by Shazka Systems.", ffont);
//
//                 ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
//                         footer,
//                         (my_pdf_report.right() - my_pdf_report.left()) / 2 + my_pdf_report.leftMargin(),
//                         my_pdf_report.bottom() - 10, 0);
                
                Paragraph titl = new Paragraph("KSU Student Mess System Report", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Font.BOLD, BaseColor.RED));
                                                titl.setAlignment(Element.ALIGN_CENTER);
                                                my_pdf_report.add(titl);
                                                Paragraph titl2 = new Paragraph("P.O BOX 408-40200", FontFactory.getFont(FontFactory.HELVETICA, 18, Font.BOLD, BaseColor.RED));
                                                titl2.setAlignment(Element.ALIGN_CENTER);
                                                my_pdf_report.add(titl2);
                                                        Paragraph titl3 = new Paragraph("Kisii", FontFactory.getFont(FontFactory.HELVETICA, 18, Font.BOLD, BaseColor.RED));
                                                titl3.setAlignment(Element.ALIGN_CENTER);
                                                my_pdf_report.add(titl3);
                                                         Paragraph titl4 = new Paragraph("******************", FontFactory.getFont(FontFactory.HELVETICA, 18, Font.BOLD, BaseColor.RED));
                                                titl4.setAlignment(Element.ALIGN_CENTER);
                                                my_pdf_report.add(titl4);
                                                
                                                
                                                       
                                                
                
           // Font ffont = new Font(Font.FontFamily.UNDEFINED, 6, Font.ITALIC);
                
//                String t1 = "RegNo";
//                                table_cell=new PdfPCell(new Phrase(t1,FontFactory.getFont(FontFactory.HELVETICA, 10, Font.BOLD)));
//                                my_report_table.addCell(table_cell);
//                                
//                String t2 = "Date";
//                                table_cell=new PdfPCell(new Phrase(t2,FontFactory.getFont(FontFactory.HELVETICA, 10, Font.BOLD)));
//                                my_report_table.addCell(table_cell);
//                               
//                                
//               String t3 = "Time";
//                                table_cell=new PdfPCell(new Phrase(t3, FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
//                                my_report_table.addCell(table_cell);
//                                
              String t4 = "Ugali";
                                table_cell=new PdfPCell(new Phrase(t4,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
               String t5 = "Rice";
                                table_cell=new PdfPCell(new Phrase(t5,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
               String t6 = "Chapati";
                                table_cell=new PdfPCell(new Phrase(t6,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                 String t7 = "Githeri";
                                table_cell=new PdfPCell(new Phrase(t7,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
                String t8 = "Cabbage";
                                table_cell=new PdfPCell(new Phrase(t8,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                               
                                
               String t9 = "Kales";
                                table_cell=new PdfPCell(new Phrase(t9, FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
              String t10 = "Beef";
                                table_cell=new PdfPCell(new Phrase(t10,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
               String t11 = "Eggs";
                                table_cell=new PdfPCell(new Phrase(t11,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
               String t12 = "Tea";
                                table_cell=new PdfPCell(new Phrase(t12,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                 String t13 = "Ndazi";
                                table_cell=new PdfPCell(new Phrase(t13,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
               String t14 = "Beans";
                                table_cell=new PdfPCell(new Phrase(t14,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
                                
               String t15 = "Total";
                                table_cell=new PdfPCell(new Phrase(t15,FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
                                my_report_table.addCell(table_cell);
               
                while (query_set.next()) {                
//                                String dept_id = query_set.getString("RegNo");
//                                table_cell=new PdfPCell(new Phrase(dept_id));
//                                my_report_table.addCell(table_cell);
//                                String dept_name=query_set.getString("Date");
//                                table_cell=new PdfPCell(new Phrase(dept_name));
//                                my_report_table.addCell(table_cell);
//                                String manager_id=query_set.getString("Time");
//                                table_cell=new PdfPCell(new Phrase(manager_id));
//                                my_report_table.addCell(table_cell);
                                String location_id=query_set.getString("Ugali");
                                table_cell=new PdfPCell(new Phrase(location_id));
                                my_report_table.addCell(table_cell);
                                
                                String kk=query_set.getString("Rice");
                                table_cell=new PdfPCell(new Phrase(kk));
                                my_report_table.addCell(table_cell);
                                String kk2=query_set.getString("Chapati");
                                table_cell=new PdfPCell(new Phrase(kk2));
                                my_report_table.addCell(table_cell);
                                
                                 String dept_id1= query_set.getString("Githeri");
                                table_cell=new PdfPCell(new Phrase(dept_id1));
                                my_report_table.addCell(table_cell);
                                
                                String dept_name1=query_set.getString("Cabbage");
                                table_cell=new PdfPCell(new Phrase(dept_name1));
                                my_report_table.addCell(table_cell);
                                
                                String manager_id1=query_set.getString("Kales");
                                table_cell=new PdfPCell(new Phrase(manager_id1));
                                my_report_table.addCell(table_cell);
                                
                                String location_id1=query_set.getString("Beef");
                                table_cell=new PdfPCell(new Phrase(location_id1));
                                my_report_table.addCell(table_cell);
                                
                                String kk1=query_set.getString("Eggs");
                                table_cell=new PdfPCell(new Phrase(kk1));
                                my_report_table.addCell(table_cell);
                                
                                String kk21=query_set.getString("Tea");
                                table_cell=new PdfPCell(new Phrase(kk21));
                                my_report_table.addCell(table_cell);
                                
                                 String location_id11=query_set.getString("Ndazi");
                                table_cell=new PdfPCell(new Phrase(location_id11));
                                my_report_table.addCell(table_cell);
                                
                                String kk11=query_set.getString("Beans");
                                table_cell=new PdfPCell(new Phrase(kk11));
                                my_report_table.addCell(table_cell);
                                
                                String kk211=query_set.getString("Total");
                                table_cell=new PdfPCell(new Phrase(kk211));
                                my_report_table.addCell(table_cell);
                                
                                }
                /* Attach report table to PDF */
                
                 try{

                                                File myFile = new File("records.pdf");
                                                Desktop.getDesktop().open(myFile);
                                            }catch(Exception e){
                                            JOptionPane.showMessageDialog(null, e);
                                            }
                my_pdf_report.add(my_report_table);                       
              my_pdf_report.close();
                 my_pdf_report.open();
                /* Close all DB related objects */
                query_set.close();
                stmt.close(); 
                conn.close();               
                
        }
}
