/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Shazka
 */
public class Login_Frame extends javax.swing.JFrame {
    int timeRun;
        Connection conn = null;
       PreparedStatement pst =  null;
        
       ResultSet rs = null;
    /**
     * Creates new form Login_Frame
     */
    public Login_Frame() {
        initComponents();
        select();
        time();
                jPswd.setEnabled(true);
                karisload.setVisible(true);

                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        com_sel = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPswd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        karisload = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Clock = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setShape(getShape());
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("OPERATOR LOGIN PANEL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 26, 360, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Select operator");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 83, 138, -1));

        com_sel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        com_sel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Student", "User", "Administrator" }));
        com_sel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                com_selItemStateChanged(evt);
            }
        });
        com_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_selActionPerformed(evt);
            }
        });
        jPanel1.add(com_sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 79, 172, 25));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Operator password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPswd.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jPswd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPswdActionPerformed(evt);
            }
        });
        jPswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPswdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPswdKeyReleased(evt);
            }
        });
        jPanel1.add(jPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 171, 172, 25));

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 224, -1, 32));

        jButton2.setText("CLEAR");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 224, -1, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PadLock-icon.png"))); // NOI18N
        jLabel3.setToolTipText("STAFF ALTERNATIVE LOG IN");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 26, -1, 50));

        karisload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Loading-Animated-GIF.gif"))); // NOI18N
        karisload.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                karisloadComponentHidden(evt);
            }
        });
        jPanel1.add(karisload, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 238, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("User Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 132, 138, -1));

        jTname.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jTname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTnameMouseClicked(evt);
            }
        });
        jPanel1.add(jTname, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 128, 172, 25));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/public.png"))); // NOI18N
        jLabel1.setToolTipText("Close");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 29, 30));

        jLabel8.setText("Note: password and user name are case sensitive");

        Clock.setFont(new java.awt.Font("DS-Digital", 0, 18)); // NOI18N
        Clock.setForeground(new java.awt.Color(204, 0, 204));
        Clock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        Clock.setText("time");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_16.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Clock, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clock)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void com_selItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_com_selItemStateChanged

    }//GEN-LAST:event_com_selItemStateChanged

    private void jPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPswdActionPerformed

    private void jPswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPswdKeyPressed
       
    }//GEN-LAST:event_jPswdKeyPressed

    private void jPswdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPswdKeyReleased

    }//GEN-LAST:event_jPswdKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String name="shazka";
       String pass="2355";
       
       String name2=jTname.getText();
       String pass2=jPswd.getText();
       
       if (pass.equals(pass2)&&name.equals(name2)){
       MainFrame kk=new MainFrame();
       kk.setVisible(true);
       this.dispose();
       }else 
           JOptionPane.showMessageDialog(null, "Wrong User name or Password \n Try again");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //        connection connect=new connection();
      
    }//GEN-LAST:event_jLabel3MouseClicked

    private void karisloadComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_karisloadComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_karisloadComponentHidden

    private void com_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_selActionPerformed
        select();
    }//GEN-LAST:event_com_selActionPerformed

    private void jTnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTnameMouseClicked
        jTname.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12));
        jTname.setText("");
    }//GEN-LAST:event_jTnameMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clock;
    private javax.swing.JComboBox com_sel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPswd;
    private javax.swing.JTextField jTname;
    private javax.swing.JLabel karisload;
    // End of variables declaration//GEN-END:variables

    public void select(){
       String choice;
       choice=(String)com_sel.getSelectedItem();
       
       if(choice=="--Select--"){
       jTname.setEnabled(false);
       jPswd.setEnabled(false);
     //  jPswd.setBackground(204,204,255);
       }
       else
           if(choice=="User"){
               jTname.setFont(new java.awt.Font("Roman", 1, 9));
       jTname.setText("Enter Your Staff Number");
        jTname.setEnabled(true);
       jPswd.setVisible(true);
       }
       else
               if(choice=="Student"){
                   jTname.setFont(new java.awt.Font("Roman", 1, 9));
       jTname.setText("Enter Your Registration Number");
       jTname.setEnabled(true);
       jPswd.setVisible(true);
       }
       else
                   if(choice=="Administrator"){
                       jTname.setEnabled(true);
       jPswd.setVisible(true);
         
       
       
       }
       
               
               }
    
    public void time(){
           
        new Thread (){
        public void run(){
        while (timeRun==0){
            Calendar kk=new GregorianCalendar ();
            int hour=kk.get(Calendar.HOUR);
            int min=kk.get(Calendar.MINUTE);
            int sec=kk.get(Calendar.SECOND);
            int AM_PM=kk.get(Calendar.AM_PM);
            int macro=kk.get(Calendar.MILLISECOND);
            int month=kk.get(Calendar.MONTH);
            int year=kk.get(Calendar.YEAR);
            String dert,karis;
            if(AM_PM==0){
            dert="AM";
            }
            else 
                dert="PM";
            if(hour<10){
            karis="0"+hour+":"+min+":"+sec+":"+dert;
            }else
                if(min<10){
            karis=hour+":"+"0"+min+":"+sec+":"+dert;
            }else
                    if(sec<10){
            karis=hour+":"+min+":"+"0"+sec+":"+dert;
            }else
              if(hour==0){
            karis="12"+":"+min+":"+sec+":"+dert;
            }
            else
            karis=hour+":"+min+":"+sec+":"+dert;
            Clock.setText(karis);
            
              }
        }
        
        }.start();
        GregorianCalendar kk=new GregorianCalendar();
        DateFormat karis= DateFormat.getDateInstance();
        java.util.Date java=kk.getTime();
        String s=karis.format(java);
        } 
   
            public void login (){
    
          String student;
          
          JOptionPane.showMessageDialog(null, "Saved Successfully");
            }
}
