/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess_system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Shazka
 */
public class Progress extends javax.swing.JFrame {
        
     int timeRun = 0;
 private Timer t;
 private ActionListener al;

    /**
     * Creates new form Progress
     */
    public Progress() {
        initComponents();
        progress();
         t.start();
        try{
        Thread.sleep(2500);
        }catch(Exception ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        load1 = new javax.swing.JLabel();
        load2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(540, 530));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(893, 444, 121, 0);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(0, 280, 400, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/globe.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 54, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/globe.gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 10, 70, 61);

        load1.setFont(new java.awt.Font("Texas LED", 0, 24)); // NOI18N
        load1.setForeground(new java.awt.Color(255, 255, 0));
        load1.setText("Loading . . . ");
        getContentPane().add(load1);
        load1.setBounds(140, 250, 135, 20);

        load2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/Loading-Animated-GIF.gif"))); // NOI18N
        getContentPane().add(load2);
        load2.setBounds(110, 210, 170, 18);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/preloader_large.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Progress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel load1;
    private javax.swing.JLabel load2;
    // End of variables declaration//GEN-END:variables

        public void progress(){
   al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
          
                if (jProgressBar1.getValue() < 100) {
                    jProgressBar1.setValue(jProgressBar1.getValue() + 1);
                        //getToolkit().beep();  
                    
                     if(((jProgressBar1.getValue()%5)==0)&&(jProgressBar1.getValue()<90)){
                    //  getToolkit().beep(); 
                    }
                     
                     if(jProgressBar1.getValue()>90){
                     // getToolkit().beep(); 
                    }
                     
                    if(jProgressBar1.getValue()==100){
                        
                    }
                } 
                
                
                
                else {
                    t.stop();
                     dispose(); 
                    admin_log kk=new admin_log();
                     
                   //  trial kk=new trial();
                    kk.setVisible(true);
//                   admin_log log=new admin_log();
//                        log.setVisible(true);
                
                      
                    
                   

       
                }
            }
        };
        t = new Timer(200, al);
        t.start();
        try{
        Thread.sleep(20);
        }catch(Exception ex){}
   }
}
