/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess_system;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Karis
 */
public class Reports_Platform extends javax.swing.JDialog {
        Statement stm=null;
 Connection conn = null;
PreparedStatement pst =  null;
ResultSet rs = null;

     getMean gm = new getMean();
    /**
     * Creates new form Reports_Platform
     */
    public Reports_Platform(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCday = new javax.swing.JComboBox();
        jCmonth = new javax.swing.JComboBox();
        jCyear = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Daily = new javax.swing.JTable();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Monthly = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane12 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Annual = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_All = new javax.swing.JTable();
        jBdaily = new javax.swing.JButton();
        jBmonthly = new javax.swing.JButton();
        jBannual = new javax.swing.JButton();
        jBall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select Date :");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jCday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Day--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCmonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCmonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Month--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jCmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmonthActionPerformed(evt);
            }
        });

        jCyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Year--", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        jLabel38.setFont(new java.awt.Font("Viner Hand ITC", 2, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 0));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ProgressRoller.gif"))); // NOI18N
        jLabel38.setText(" Refresh . . . ");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jTabbedPane6.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jTable_Daily.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reference", "Ugali", "Rice", "Chapati", "Githeri", "Cabbage", "Kales", "Beef", "Eggs", "Tea", "Ndazi", "Beans", "Total", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Daily);

        jTabbedPane6.addTab("", jScrollPane1);

        jTabbedPane2.addTab("Daily Total Income", jTabbedPane6);

        jTabbedPane1.addTab("Daily Reports     ", jTabbedPane2);

        jTabbedPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane5MouseClicked(evt);
            }
        });

        jTabbedPane10.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jTable_Monthly.setAutoCreateRowSorter(true);
        jTable_Monthly.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reference", "Ugali", "Rice", "Chapati", "Githeri", "Cabbage", "Kales", "Beef", "Eggs", "Tea", "Ndazi", "Beans", "Total", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Monthly);

        jTabbedPane10.addTab("", jScrollPane3);

        jTabbedPane5.addTab("Total Monthly Income Cash", jTabbedPane10);

        jTabbedPane1.addTab("Monthly  Reports   ", jTabbedPane5);

        jTabbedPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane4MouseClicked(evt);
            }
        });

        jTabbedPane12.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jTable_Annual.setAutoCreateRowSorter(true);
        jTable_Annual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reference", "Ugali", "Rice", "Chapati", "Githeri", "Cabbage", "Kales", "Beef", "Eggs", "Tea", "Ndazi", "Beans", "Total", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_Annual);

        jTabbedPane12.addTab("", jScrollPane4);

        jTabbedPane4.addTab("Annual Total Income   ", jTabbedPane12);

        jTabbedPane1.addTab("Annual  Reports     ", jTabbedPane4);

        jTabbedPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane3MouseClicked(evt);
            }
        });

        jTabbedPane8.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jTable_All.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reference", "Ugali", "Rice", "Chapati", "Githeri", "Cabbage", "Kales", "Beef", "Eggs", "Tea", "Ndazi", "Beans", "Total", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_All);

        jTabbedPane8.addTab("", jScrollPane2);

        jTabbedPane3.addTab("All Total Income", jTabbedPane8);

        jTabbedPane1.addTab("All  Reports     ", jTabbedPane3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBdaily.setText("Print Daily Report");
        jBdaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdailyActionPerformed(evt);
            }
        });

        jBmonthly.setText("Print Monthy Report");
        jBmonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmonthlyActionPerformed(evt);
            }
        });

        jBannual.setText("Print Annual Report");
        jBannual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBannualActionPerformed(evt);
            }
        });

        jBall.setText("Print All Reports");
        jBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jCday, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jCmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jCyear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jBdaily, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jBannual, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jBmonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jBall, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBdaily, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBannual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmonthActionPerformed

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked

            //table();
//        shazka_systems();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
           table_daily();
             // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jBdailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdailyActionPerformed
         try{

            jTable_Daily.print();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBdailyActionPerformed

    private void jTabbedPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane5MouseClicked

        table_month();
    }//GEN-LAST:event_jTabbedPane5MouseClicked

    private void jTabbedPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane4MouseClicked
            table_year();        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane4MouseClicked

    private void jTabbedPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane3MouseClicked
        table_All();        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane3MouseClicked

    private void jBannualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBannualActionPerformed
         try{

            jdbc_pdf_report kk=new jdbc_pdf_report();
       kk.mainh();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }           // TODO add your handling code here:
    }//GEN-LAST:event_jBannualActionPerformed

    private void jBmonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmonthlyActionPerformed
         try{

            jdbc_pdf_report kk=new jdbc_pdf_report();
       kk.mainh();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }           // TODO add your handling code here:
    }//GEN-LAST:event_jBmonthlyActionPerformed

    private void jBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBallActionPerformed
       try{
       
       jdbc_pdf_report kk=new jdbc_pdf_report();
       kk.mainh();
       }catch(Exception ex){}
       
    }//GEN-LAST:event_jBallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports_Platform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports_Platform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports_Platform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports_Platform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reports_Platform dialog = new Reports_Platform(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBall;
    private javax.swing.JButton jBannual;
    private javax.swing.JButton jBdaily;
    private javax.swing.JButton jBmonthly;
    private javax.swing.JComboBox jCday;
    private javax.swing.JComboBox jCmonth;
    private javax.swing.JComboBox jCyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTable jTable_All;
    private javax.swing.JTable jTable_Annual;
    private javax.swing.JTable jTable_Daily;
    private javax.swing.JTable jTable_Monthly;
    // End of variables declaration//GEN-END:variables

          public void table_All(){
    
            String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            String as = "SELECT*FROM records";
            ResultSet rs = s.executeQuery(as);
            //pst=conn.prepareStatement(as);
            //rs=pst.executeQuery();
            int r = 0;
            int records = 0;
            while (rs.next()) {
                //table_optical.setModel(DbUtils.resultSetToTableModel(rs));
////                jTable_Daily.setValueAt(rs.getString("Id"), r, 0);
////                jTable_Daily.setValueAt(rs.getString("Ugali"), r, 1);
////                jTable_Daily.setValueAt(rs.getString("Rice"), r, 2);
////                jTable_Daily.setValueAt(rs.getString("Chapati"), r, 3);
////                jTable_Daily.setValueAt(rs.getString("Githeri"), r, 4);
////                jTable_Daily.setValueAt(rs.getString("Cabbage"), r, 5);
////                jTable_Daily.setValueAt(rs.getString("Kales"), r, 6);
////                jTable_Daily.setValueAt(rs.getString("Beef"), r, 7);
////                jTable_Daily.setValueAt(rs.getString("Eggs"), r, 8);
////                jTable_Daily.setValueAt(rs.getString("Tea"), r, 9);
////                jTable_Daily.setValueAt(rs.getString("Ndazi"), r, 10);
////                jTable_Daily.setValueAt(rs.getString("Beans"), r, 11);
////                jTable_Daily.setValueAt(rs.getString("Total"), r, 12);
////                jTable_Daily.setValueAt(rs.getString("Date"), r, 13);
////                jTable_Daily.setValueAt(rs.getString("Time"), r, 14);
                
                 jTable_All.setValueAt(rs.getString("Id"), r, 0);
                jTable_All.setValueAt(rs.getString("Ugali"), r, 1);
                jTable_All.setValueAt(rs.getString("Rice"), r, 2);
                jTable_All.setValueAt(rs.getString("Chapati"), r, 3);
                jTable_All.setValueAt(rs.getString("Githeri"), r, 4);
                jTable_All.setValueAt(rs.getString("Cabbage"), r, 5);
                jTable_All.setValueAt(rs.getString("Kales"), r, 6);
                jTable_All.setValueAt(rs.getString("Beef"), r, 7);
                jTable_All.setValueAt(rs.getString("Eggs"), r, 8);
                jTable_All.setValueAt(rs.getString("Tea"), r, 9);
                jTable_All.setValueAt(rs.getString("Ndazi"), r, 10);
                jTable_All.setValueAt(rs.getString("Beans"), r, 11);
                jTable_All.setValueAt(rs.getString("Total"), r, 12);
                jTable_All.setValueAt(rs.getString("Date"), r, 13);
                jTable_All.setValueAt(rs.getString("Time"), r, 14);
                
//                 jTable_Monthly.setValueAt(rs.getString("Id"), r, 0);
//                jTable_Monthly.setValueAt(rs.getString("Ugali"), r, 1);
//                jTable_Monthly.setValueAt(rs.getString("Rice"), r, 2);
//                jTable_Monthly.setValueAt(rs.getString("Chapati"), r, 3);
//                jTable_Monthly.setValueAt(rs.getString("Githeri"), r, 4);
//                jTable_Monthly.setValueAt(rs.getString("Cabbage"), r, 5);
//                jTable_Monthly.setValueAt(rs.getString("Kales"), r, 6);
//                jTable_Monthly.setValueAt(rs.getString("Beef"), r, 7);
//                jTable_Monthly.setValueAt(rs.getString("Eggs"), r, 8);
//                jTable_Monthly.setValueAt(rs.getString("Tea"), r, 9);
//                jTable_Monthly.setValueAt(rs.getString("Ndazi"), r, 10);
//                jTable_Monthly.setValueAt(rs.getString("Beans"), r, 11);
//                jTable_Monthly.setValueAt(rs.getString("Total"), r, 12);
//                jTable_Monthly.setValueAt(rs.getString("Date"), r, 13);
//                jTable_Monthly.setValueAt(rs.getString("Time"), r, 14);
//                
//                 jTable_Annual.setValueAt(rs.getString("Id"), r, 0);
//                jTable_Annual.setValueAt(rs.getString("Ugali"), r, 1);
//                jTable_Annual.setValueAt(rs.getString("Rice"), r, 2);
//                jTable_Annual.setValueAt(rs.getString("Chapati"), r, 3);
//                jTable_Annual.setValueAt(rs.getString("Githeri"), r, 4);
//                jTable_Annual.setValueAt(rs.getString("Cabbage"), r, 5);
//                jTable_Annual.setValueAt(rs.getString("Kales"), r, 6);
//                jTable_Annual.setValueAt(rs.getString("Beef"), r, 7);
//                jTable_Annual.setValueAt(rs.getString("Eggs"), r, 8);
//                jTable_Annual.setValueAt(rs.getString("Tea"), r, 9);
//                jTable_Annual.setValueAt(rs.getString("Ndazi"), r, 10);
//                jTable_Annual.setValueAt(rs.getString("Beans"), r, 11);
//                jTable_Annual.setValueAt(rs.getString("Total"), r, 12);
//                jTable_Annual.setValueAt(rs.getString("Date"), r, 13);
//                jTable_Annual.setValueAt(rs.getString("Time"), r, 14);
                

                r++;

            }
          
        } catch (SQLException m) {
            JOptionPane.showMessageDialog(null, m);
        }
    }

         
          public void table_daily(){
    
                      String day=(String)jCday.getSelectedItem();
                      String month=(String)jCmonth.getSelectedItem();
                      String year=(String)jCyear.getSelectedItem();
            String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            String as = "SELECT * FROM `records` WHERE `Day`='"+day+"' AND `Month`='"+month+"' AND `Year`='"+year+"'";
            ResultSet rs = s.executeQuery(as);
            //pst=conn.prepareStatement(as);
            //rs=pst.executeQuery();
            int r = 0;
            int records = 0;
            while (rs.next()) {
                //table_optical.setModel(DbUtils.resultSetToTableModel(rs));
                jTable_Daily.setValueAt(rs.getString("Id"), r, 0);
                jTable_Daily.setValueAt(rs.getString("Ugali"), r, 1);
                jTable_Daily.setValueAt(rs.getString("Rice"), r, 2);
                jTable_Daily.setValueAt(rs.getString("Chapati"), r, 3);
                jTable_Daily.setValueAt(rs.getString("Githeri"), r, 4);
                jTable_Daily.setValueAt(rs.getString("Cabbage"), r, 5);
                jTable_Daily.setValueAt(rs.getString("Kales"), r, 6);
                jTable_Daily.setValueAt(rs.getString("Beef"), r, 7);
                jTable_Daily.setValueAt(rs.getString("Eggs"), r, 8);
                jTable_Daily.setValueAt(rs.getString("Tea"), r, 9);
                jTable_Daily.setValueAt(rs.getString("Ndazi"), r, 10);
                jTable_Daily.setValueAt(rs.getString("Beans"), r, 11);
                jTable_Daily.setValueAt(rs.getString("Total"), r, 12);
                jTable_Daily.setValueAt(rs.getString("Date"), r, 13);
                jTable_Daily.setValueAt(rs.getString("Time"), r, 14);
                

                r++;

            }
          
        } catch (SQLException m) {
            JOptionPane.showMessageDialog(null, m);
        }
    }

    
          public void table_month(){
    
                      String day=(String)jCday.getSelectedItem();
                      String month=(String)jCmonth.getSelectedItem();
                      String year=(String)jCyear.getSelectedItem();
            String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            String as = "SELECT * FROM `records` WHERE `Month`='"+month+"' AND `Year`='"+year+"'";
            ResultSet rs = s.executeQuery(as);
            //pst=conn.prepareStatement(as);
            //rs=pst.executeQuery();
            int r = 0;
            int records = 0;
            while (rs.next()) {
                //table_optical.setModel(DbUtils.resultSetToTableModel(rs));
//                jTable_Daily.setValueAt(rs.getString("Id"), r, 0);
//                jTable_Daily.setValueAt(rs.getString("Ugali"), r, 1);
//                jTable_Daily.setValueAt(rs.getString("Rice"), r, 2);
//                jTable_Daily.setValueAt(rs.getString("Chapati"), r, 3);
//                jTable_Daily.setValueAt(rs.getString("Githeri"), r, 4);
//                jTable_Daily.setValueAt(rs.getString("Cabbage"), r, 5);
//                jTable_Daily.setValueAt(rs.getString("Kales"), r, 6);
//                jTable_Daily.setValueAt(rs.getString("Beef"), r, 7);
//                jTable_Daily.setValueAt(rs.getString("Eggs"), r, 8);
//                jTable_Daily.setValueAt(rs.getString("Tea"), r, 9);
//                jTable_Daily.setValueAt(rs.getString("Ndazi"), r, 10);
//                jTable_Daily.setValueAt(rs.getString("Beans"), r, 11);
//                jTable_Daily.setValueAt(rs.getString("Total"), r, 12);
//                jTable_Daily.setValueAt(rs.getString("Date"), r, 13);
//                jTable_Daily.setValueAt(rs.getString("Time"), r, 14);
                
//                 jTable_All.setValueAt(rs.getString("Id"), r, 0);
//                jTable_All.setValueAt(rs.getString("Ugali"), r, 1);
//                jTable_All.setValueAt(rs.getString("Rice"), r, 2);
//                jTable_All.setValueAt(rs.getString("Chapati"), r, 3);
//                jTable_All.setValueAt(rs.getString("Githeri"), r, 4);
//                jTable_All.setValueAt(rs.getString("Cabbage"), r, 5);
//                jTable_All.setValueAt(rs.getString("Kales"), r, 6);
//                jTable_All.setValueAt(rs.getString("Beef"), r, 7);
//                jTable_All.setValueAt(rs.getString("Eggs"), r, 8);
//                jTable_All.setValueAt(rs.getString("Tea"), r, 9);
//                jTable_All.setValueAt(rs.getString("Ndazi"), r, 10);
//                jTable_All.setValueAt(rs.getString("Beans"), r, 11);
//                jTable_All.setValueAt(rs.getString("Total"), r, 12);
//                jTable_All.setValueAt(rs.getString("Date"), r, 13);
//                jTable_All.setValueAt(rs.getString("Time"), r, 14);
//                
                 jTable_Monthly.setValueAt(rs.getString("Id"), r, 0);
                jTable_Monthly.setValueAt(rs.getString("Ugali"), r, 1);
                jTable_Monthly.setValueAt(rs.getString("Rice"), r, 2);
                jTable_Monthly.setValueAt(rs.getString("Chapati"), r, 3);
                jTable_Monthly.setValueAt(rs.getString("Githeri"), r, 4);
                jTable_Monthly.setValueAt(rs.getString("Cabbage"), r, 5);
                jTable_Monthly.setValueAt(rs.getString("Kales"), r, 6);
                jTable_Monthly.setValueAt(rs.getString("Beef"), r, 7);
                jTable_Monthly.setValueAt(rs.getString("Eggs"), r, 8);
                jTable_Monthly.setValueAt(rs.getString("Tea"), r, 9);
                jTable_Monthly.setValueAt(rs.getString("Ndazi"), r, 10);
                jTable_Monthly.setValueAt(rs.getString("Beans"), r, 11);
                jTable_Monthly.setValueAt(rs.getString("Total"), r, 12);
                jTable_Monthly.setValueAt(rs.getString("Date"), r, 13);
                jTable_Monthly.setValueAt(rs.getString("Time"), r, 14);
//                
//                 jTable_Annual.setValueAt(rs.getString("Id"), r, 0);
//                jTable_Annual.setValueAt(rs.getString("Ugali"), r, 1);
//                jTable_Annual.setValueAt(rs.getString("Rice"), r, 2);
//                jTable_Annual.setValueAt(rs.getString("Chapati"), r, 3);
//                jTable_Annual.setValueAt(rs.getString("Githeri"), r, 4);
//                jTable_Annual.setValueAt(rs.getString("Cabbage"), r, 5);
//                jTable_Annual.setValueAt(rs.getString("Kales"), r, 6);
//                jTable_Annual.setValueAt(rs.getString("Beef"), r, 7);
//                jTable_Annual.setValueAt(rs.getString("Eggs"), r, 8);
//                jTable_Annual.setValueAt(rs.getString("Tea"), r, 9);
//                jTable_Annual.setValueAt(rs.getString("Ndazi"), r, 10);
//                jTable_Annual.setValueAt(rs.getString("Beans"), r, 11);
//                jTable_Annual.setValueAt(rs.getString("Total"), r, 12);
//                jTable_Annual.setValueAt(rs.getString("Date"), r, 13);
//                jTable_Annual.setValueAt(rs.getString("Time"), r, 14);
                

                r++;

            }
          
        } catch (SQLException m) {
            JOptionPane.showMessageDialog(null, m);
        }
    }
          
                  
         public void table_year(){
    
                      String day=(String)jCday.getSelectedItem();
                      String month=(String)jCmonth.getSelectedItem();
                      String year=(String)jCyear.getSelectedItem();
            String dbnam = "mess";
        String pwd = "";
        String usernam = "root";
        String Driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/";
        Connection cn = null;
        try {

            Class.forName(Driver).newInstance();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        try {
            cn = DriverManager.getConnection(url + dbnam, usernam, pwd);
            Statement s = cn.createStatement();
            String as = "SELECT * FROM `records` WHERE `Year`='"+year+"'";
            ResultSet rs = s.executeQuery(as);
            //pst=conn.prepareStatement(as);
            //rs=pst.executeQuery();
            int r = 0;
            int records = 0;
            while (rs.next()) {
                
               jTable_Annual.setValueAt(rs.getString("Id"), r, 0);
                jTable_Annual.setValueAt(rs.getString("Ugali"), r, 1);
                jTable_Annual.setValueAt(rs.getString("Rice"), r, 2);
                jTable_Annual.setValueAt(rs.getString("Chapati"), r, 3);
                jTable_Annual.setValueAt(rs.getString("Githeri"), r, 4);
                jTable_Annual.setValueAt(rs.getString("Cabbage"), r, 5);
                jTable_Annual.setValueAt(rs.getString("Kales"), r, 6);
                jTable_Annual.setValueAt(rs.getString("Beef"), r, 7);
                jTable_Annual.setValueAt(rs.getString("Eggs"), r, 8);
                jTable_Annual.setValueAt(rs.getString("Tea"), r, 9);
                jTable_Annual.setValueAt(rs.getString("Ndazi"), r, 10);
                jTable_Annual.setValueAt(rs.getString("Beans"), r, 11);
                jTable_Annual.setValueAt(rs.getString("Total"), r, 12);
                jTable_Annual.setValueAt(rs.getString("Date"), r, 13);
                jTable_Annual.setValueAt(rs.getString("Time"), r, 14);
                

                r++;

            }
          
        } catch (SQLException m) {
            JOptionPane.showMessageDialog(null, m);
        }
    }

    

    
}
