/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess_system;

import com.sun.glass.events.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Shazka
 */
public class Staff_Sign extends javax.swing.JInternalFrame {
        int tymRun;
        Connection conn = null;
       PreparedStatement pst =  null;
       ResultSet rs = null;
    /**
     * Creates new form Staff_Reg
     */
    public Staff_Sign() {
        initComponents();
       
          int num;
        Random kkk = new Random();
        num = kkk.nextInt((9999) + 2000);
       // jTpswd.setText(String.valueOf(num));
        getToolkit().beep();
        
       // path.setVisible(false);
        path1.setVisible(false);
       // jTtym.setText("loading time...");
          
        
         new Thread (){
                @Override
    public void run(){
               
           while (tymRun==0){
               Calendar kk= new GregorianCalendar();
               int hour=kk.get(Calendar.HOUR);
               int min=kk.get(Calendar.MINUTE);
               int sec=kk.get(Calendar.SECOND);
               int AM_PM=kk.get(Calendar.AM_PM);
               
          String dert;
          if(AM_PM==0){
          dert="AM";
          }
          else
              dert="PM";
          String karis;
                if (hour==0){
                 karis="12"+":"+min+":"+sec+" "+dert;}
                else
                  karis=hour+":"+min+":"+sec+" "+dert;
                  //Clock.setText(karis);
           }
               
       }
    }.start();
        
        GregorianCalendar today = new GregorianCalendar();
        DateFormat df = DateFormat.getDateInstance();
        Date kk = today.getTime();
        String s = df.format(kk);
       // jTdate.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jTdepertment1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTphoneNo2 = new javax.swing.JTextField();
        jTfname2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTsurname2 = new javax.swing.JTextField();
        jTmName2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTbox1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTidnumber2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTstaffNo1 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jTdoE1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTsupervisor1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jCgender2 = new javax.swing.JComboBox();
        jTtym2 = new javax.swing.JTextField();
        jTemail2 = new javax.swing.JTextField();
        jTpswd2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTdate2 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTsupervNo1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        image1 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        Clock2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        path1 = new javax.swing.JTextField();
        jBupdate1 = new javax.swing.JButton();
        jBdelete = new javax.swing.JButton();
        jTsearch1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Staff Registration Panel");
        setToolTipText("Powered By Shazka Systems");

        jPanel5.setLayout(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Staff Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Calligraphy", 0, 12), new java.awt.Color(0, 255, 0))); // NOI18N

        jTdepertment1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/applications.png"))); // NOI18N
        jLabel24.setText("Staff No.");

        jTphoneNo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTphoneNo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTphoneNo2KeyTyped(evt);
            }
        });

        jTfname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loading-1.png"))); // NOI18N
        jLabel25.setText(" Department ");

        jTsurname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTmName2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_16.png"))); // NOI18N
        jLabel26.setText("   ID Number");

        jTbox1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_48x48.png"))); // NOI18N
        jLabel27.setText("Surname :");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Phone.png"))); // NOI18N
        jLabel28.setText("Phone No. :");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home.png"))); // NOI18N
        jLabel29.setText("P.O Box");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_48x48.png"))); // NOI18N
        jLabel30.setText("Middle Name :");

        jTidnumber2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTidnumber2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTidnumber2KeyTyped(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_48x48.png"))); // NOI18N
        jLabel31.setText("First Name :");

        jTstaffNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTmName2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTphoneNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTstaffNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTsurname2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfname2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTdepertment1)
                                    .addComponent(jTidnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTsurname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(13, 13, 13)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTfname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTmName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTstaffNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTidnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTdepertment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTphoneNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Staff Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Calligraphy", 0, 12), new java.awt.Color(0, 255, 0))); // NOI18N

        jTdoE1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_att.png"))); // NOI18N
        jLabel44.setText("Email :");

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        jLabel45.setText("Time :");

        jTsupervisor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table_add.png"))); // NOI18N
        jLabel46.setText("Date of Emp :");

        jCgender2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Male", "Female" }));
        jCgender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCgender2ActionPerformed(evt);
            }
        });

        jTtym2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTemail2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTpswd2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kifuli.png"))); // NOI18N
        jLabel47.setText("Password :");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });

        jTdate2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/data_add.png"))); // NOI18N
        jLabel48.setText("Spvc Phone No");

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table_remove.png"))); // NOI18N
        jLabel49.setText(" Supervisor");

        jTsupervNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTsupervNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsupervNo1ActionPerformed(evt);
            }
        });
        jTsupervNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTsupervNo1KeyTyped(evt);
            }
        });

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/public.png"))); // NOI18N
        jLabel50.setText("   Gender :");

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notebook.png"))); // NOI18N
        jLabel51.setText("Date :");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jTemail2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTdoE1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCgender2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTpswd2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTtym2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(jTdate2))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTsupervNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTsupervisor1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCgender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTdoE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTsupervisor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTsupervNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTtym2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jTpswd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMAGE [.png and size (150 X 150) ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane2.setMaximumSize(new java.awt.Dimension(170, 170));
        jDesktopPane2.setMinimumSize(new java.awt.Dimension(150, 150));
        jDesktopPane2.setPreferredSize(new java.awt.Dimension(170, 170));

        image1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        image1.setForeground(new java.awt.Color(255, 255, 255));
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mess_system/icon.jpg"))); // NOI18N
        image1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jDesktopPane2.setLayer(image1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Loading-Animated-GIF.gif"))); // NOI18N

        Clock2.setFont(new java.awt.Font("LcdD", 1, 14)); // NOI18N
        Clock2.setText("jLabel18");

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/Browser.png"))); // NOI18N
        jButton6.setText("Attach");
        jButton6.setToolTipText("CLICK TO ATTACH IMAGE [png and size (150X150)]");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(path1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Clock2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Clock2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(path1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jBupdate1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/user_add_32.png"))); // NOI18N
        jBupdate1.setText(" SIGN  IN");
        jBupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBupdate1ActionPerformed(evt);
            }
        });

        jBdelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details/close_16.png"))); // NOI18N
        jBdelete.setText(" SIGN  OUT");
        jBdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBupdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBdelete, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jBdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(10, 65, 1060, 510);

        jTsearch1.setFont(new java.awt.Font("LBC Cool 2", 0, 14)); // NOI18N
        jTsearch1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTsearch1KeyReleased(evt);
            }
        });
        jPanel5.add(jTsearch1);
        jTsearch1.setBounds(250, 20, 150, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/2.png"))); // NOI18N
        jLabel18.setToolTipText("Enter Student registration number");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(240, 10, 200, 50);

        jLabel32.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/applications.png"))); // NOI18N
        jLabel32.setText("STAFF  NUMBER");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(80, 20, 150, 30);

        jTabbedPane1.addTab("Staff Sign in/Sign Out", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeleteActionPerformed
         signout();        // TODO add your handling code here:
    }//GEN-LAST:event_jBdeleteActionPerformed

    private void jBupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBupdate1ActionPerformed
         signin();        // TODO add your handling code here:
    }//GEN-LAST:event_jBupdate1ActionPerformed

    private void jTsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTsearch1KeyReleased
        search();
        image_return();
    }//GEN-LAST:event_jTsearch1KeyReleased

    private void jCgender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCgender2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCgender2ActionPerformed

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jTsupervNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsupervNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsupervNo1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTidnumber2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTidnumber2KeyTyped
             char c = evt.getKeyChar();

        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER))) {
            
            JOptionPane.showMessageDialog(null, "Enter Numerics Only");
            evt.consume();
            
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jTidnumber2KeyTyped

    private void jTphoneNo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTphoneNo2KeyTyped
         char c = evt.getKeyChar();

        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER))) {
            
            JOptionPane.showMessageDialog(null, "Enter Numerics Only");
            evt.consume();
            
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jTphoneNo2KeyTyped

    private void jTsupervNo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTsupervNo1KeyTyped
         char c = evt.getKeyChar();

        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER))) {
            
            JOptionPane.showMessageDialog(null, "Enter Numerics Only");
            evt.consume();
            
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jTsupervNo1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clock2;
    private javax.swing.JLabel image1;
    private javax.swing.JButton jBdelete;
    private javax.swing.JButton jBupdate1;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCgender2;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTbox1;
    private javax.swing.JTextField jTdate2;
    private javax.swing.JTextField jTdepertment1;
    private javax.swing.JTextField jTdoE1;
    private javax.swing.JTextField jTemail2;
    private javax.swing.JTextField jTfname2;
    private javax.swing.JTextField jTidnumber2;
    private javax.swing.JTextField jTmName2;
    private javax.swing.JTextField jTphoneNo2;
    private javax.swing.JTextField jTpswd2;
    private javax.swing.JTextField jTsearch1;
    private javax.swing.JTextField jTstaffNo1;
    private javax.swing.JTextField jTsupervNo1;
    private javax.swing.JTextField jTsupervisor1;
    private javax.swing.JTextField jTsurname2;
    private javax.swing.JTextField jTtym2;
    private javax.swing.JTextField path1;
    // End of variables declaration//GEN-END:variables
        
   public void signin(){
       
         Connect connectobj = new Connect();
                     conn = connectobj.connectdb();
                     
       String  num=jTstaffNo1.getText();
       String  sn=jTsurname2.getText();
       String  fn=jTfname2.getText();
       String  mn=jTmName2.getText();
       String  name=sn+" "+fn+" "+mn;
       String  id=jTidnumber2.getText();
       String  dep=jTdepertment1.getText();
       String  phone=jTphoneNo2.getText();
       String out="pending";
      long time = System.currentTimeMillis();
      java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
      
      try{
          
      String sql = "INSERT INTO `staffsign` (`StaffNo`,`Name`,`IdNo`,`Department`,`PhoneNo`,`SignIn`,`SignOut`) VALUE ('"+num+"','"+name+"','"+id+"','"+dep+"','"+phone+"','"+timestamp+"','"+out+"')" ;

            pst = conn.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Sign In Successfully");
      
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
   
   }
   
    public void signout(){
       
         Connect connectobj = new Connect();
                     conn = connectobj.connectdb();
                     
       String  num=jTstaffNo1.getText();
       String  sn=jTsurname2.getText();
       String  fn=jTfname2.getText();
       String  mn=jTmName2.getText();
       String  name=sn+" "+fn+" "+mn;
       String  id=jTidnumber2.getText();
       String  dep=jTdepertment1.getText();
       String  phone=jTphoneNo2.getText();
       String out="pending";
      long time = System.currentTimeMillis();
      java.sql.Timestamp timestamp = new java.sql.Timestamp(time);
      
      try{
          
      String sql = "Update `staffsign` set `SignOut`='" + timestamp + "' where`StaffNo`='" + num + "'";

            pst = conn.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Sign Out Successfully");
      
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
   
   }

    
    
   public void search(){
   
         Connect connectobj = new Connect();
        conn = connectobj.connectdb();

        String Staff = jTsearch1.getText();
        try {
            Statement stm = conn.createStatement();
            String sql = "select * from staff_details where StaffNo = '" + Staff + "'";
            rs = stm.executeQuery(sql);

            while (rs.next()) {
                    //out_table.setModel(DbUtils.resultSetToTableModel(rs));
                    String sname = rs.getString("Sname");                    
                    String fname = rs.getString("Fname");                    
                    String mname = rs.getString("Mname");                    
                    String staff = rs.getString("StaffNo");              
                    String idno = rs.getString("IdNo");
                    String dep = rs.getString("Department");
                    String box = rs.getString("PoBox");
                    
                    String phone = rs.getString("PhoneNo");                    
                    String email = rs.getString("Email");                    
                    String gender = rs.getString("Gender");                    
                    String doe = rs.getString("DoE");              
                    String spvs = rs.getString("Supervisor");
                     String number = rs.getString("SpvsPhoneNo");
                   String date = rs.getString("Date");              
                    String time = rs.getString("Time");
                                
                    String pswd = rs.getString("Pswd");
                        
                    
                    jTsurname2.setText(sname);
                    jTfname2.setText(fname);
                    jTmName2.setText(mname);
                    jTstaffNo1.setText(staff);
                    jTidnumber2.setText(idno);
                    jTdepertment1.setText(dep);
                    jTbox1.setText(box);
                    jTphoneNo2.setText(phone);
                    jTemail2.setText(email);
                    jCgender2.setSelectedItem(gender); 
                    jTdoE1.setText(doe);
                    jTsupervisor1.setText(spvs);
                    jTdate2.setText(date);
                    jTtym2.setText(time);
                    jTsupervNo1.setText(number);
                    jTpswd2.setText(pswd);
                 }

                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e.getMessage());

                            }
   }
            private javax.swing.ImageIcon format = null;

             String filename = null;
             int s = 0;
             byte[] person_image = null;
    
    
   
    public void image_return(){

                                   Connection con = null;
                            PreparedStatement pst = null;
                            ResultSet rs = null;
                            String url = "jdbc:mysql://localhost:3306/";
                            String driver = "com.mysql.jdbc.Driver";
                            String userName = "root";
                            String pwd = "";
                            String tb = "staff_images";
                           String db = "mess";
                            String util = "net.prteanit.sql.DbUtils.resultSetToTableModel";
                            try {
                                Class.forName(driver).newInstance();
                                con = DriverManager.getConnection(url + db, userName, pwd);
                                try {
                                    String querry = "SELECT * FROM " + tb + " WHERE StaffNo = ?";
                                    pst = con.prepareStatement(querry);
                                    pst.setString(1, jTsearch1.getText());
                                    rs = pst.executeQuery();
                                    if (rs.next()) {
                                         String f = rs.getString("Fname");
                                        jTfname2.setText(f);
                                         //IMAGE OUTPUT
                                        byte[] ImageData = rs.getBytes("Image");
                                        format = new javax.swing.ImageIcon(ImageData);
                                        image1.setIcon(format);

                                    }
                                } catch (SQLException e) {
                                    JOptionPane.showMessageDialog(null, "SYSTEM FAILED");
                                }
                            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException t) {
                                JOptionPane.showMessageDialog(null, "ERROR IN CONNECTION\nTHE DATA SOURCE IS CURRENTLY OFF");
                            }

                                }
    
    

}
